#!/bin/bash
rst2html.py Main_Page.rst > Main_Page.html
rst2html.py The_Horace_Rationale.rst > The_Horace_Rationale.html
rst2html.py Download_and_setup.rst > Download_and_setup.html
rst2html.py Support_and_updates.rst > Support_and_updates.html
rst2html.py Advanced_use.rst > Advanced_use.html
rst2html.py Getting_started.rst > Getting_started.html
rst2html.py List_of_functions.rst > List_of_functions.html
rst2html.py For_Developers.rst > For_Developers.html
rst2html.py Horace_GUI.rst > Horace_GUI.html
rst2html.py Horace_command_line.rst > Horace_command_line.html
rst2html.py Known_bugs.rst > Known_bugs.html
rst2html.py Remote_data_analysis.rst > Remote_data_analysis.html
rst2html.py General_disclaimer.rst > General_disclaimer.html
rst2html.py New.rst > New.html
rst2html.py Official_download_v1.rst > Official_download_v1.html
rst2html.py Generating_SQW_files.rst > Generating_SQW_files.html
rst2html.py Binary_operations.rst > Binary_operations.html
rst2html.py Unary_operations.rst > Unary_operations.html
rst2html.py Plotting.rst > Plotting.html
rst2html.py Simulation.rst > Simulation.html
rst2html.py Reshaping_etc.rst > Reshaping_etc.html
rst2html.py Read_or_write_to_disk.rst > Read_or_write_to_disk.html
rst2html.py Fitting.rst > Fitting.html
rst2html.py Privacy_policy.rst > Privacy_policy.html
rst2html.py Multifit.rst > Multifit.html
rst2html.py Changing_object_type.rst > Changing_object_type.html
rst2html.py Become_a_developer.rst > Become_a_developer.html
rst2html.py Developer_information.rst > Developer_information.html
rst2html.py s_new.rst > s_new.html
rst2html.py Papers_citing_Horace.rst > Papers_citing_Horace.html
rst2html.py Symmetrising_etc.rst > Symmetrising_etc.html
rst2html.py Horace_Masterclass.rst > Horace_Masterclass.html
rst2html.py Changing_Horace_settings.rst > Changing_Horace_settings.html
rst2html.py Herbert.rst > Herbert.html
rst2html.py Planning_a_Horace_scan.rst > Planning_a_Horace_scan.html
rst2html.py FAQ.rst > FAQ.html
rst2html.py Horace_and_Libisis_installation.rst > Horace_and_Libisis_installation.html
rst2html.py Correcting_for_sample_misalignment.rst > Correcting_for_sample_misalignment.html
rst2html.py Manipulating_and_extracting_data_from_SQW_files_and_objects.rst > Manipulating_and_extracting_data_from_SQW_files_and_objects.html
rst2html.py Example_scripts.rst > Example_scripts.html
rst2html.py Script_for_planning_an_experiment.rst > Script_for_planning_an_experiment.html
rst2html.py Script_for_generating_sqw_files.rst > Script_for_generating_sqw_files.html
rst2html.py Script_for_making_cuts_and_plotting.rst > Script_for_making_cuts_and_plotting.html
rst2html.py Script_for_data_treatment.rst > Script_for_data_treatment.html
rst2html.py Script_for_making_publication_quality_figures.rst > Script_for_making_publication_quality_figures.html
rst2html.py Script_for_making_simulations.rst > Script_for_making_simulations.html
rst2html.py Script_for_fitting.rst > Script_for_fitting.html
rst2html.py Script_for_correcting_sample_misalignment.rst > Script_for_correcting_sample_misalignment.html
rst2html.py Run_inspector.rst > Run_inspector.html
rst2html.py Developer_info.rst > Developer_info.html
rst2html.py How_to_cite_Horace.rst > How_to_cite_Horace.html
rst2html.py Input_file_formats.rst > Input_file_formats.html
rst2html.py Data_diagnostics.rst > Data_diagnostics.html
rst2html.py Tobyfit.rst > Tobyfit.html
