classdef JEwithLogTester < JobExecutor
    % Class used to test job dispatcher functionality
    % assuming that this job is run by worker, which reports its progress    
    properties
    end
    
    methods
        function je = JEwithLogTester(varargin)
            je = je@JobExecutor(varargin{:});
        end
        function this=do_job(this,control_struct)
            % Test do_job method implemented for testing purposes
            %
            % the particular JobDispatcher should write its own method
            % keeping the same meaning for the interface
            %
            % Input parameters:
            % control_struct -- a structure, containing job
            %                   parameters. 
            % this structure is generated by JobDispatcher.send_jobs method
            % by dividing array or cellarray of input parameters between
            % workers. 
            %
            % this particular implementation writes files according to template,
            % provided in test_job_dispatcher.m file
            n_steps = control_struct.n_steps;
            step    = control_struct.step;
            step    = step+1;
            mpi_obj = MPI_State.instance();
            is_deployed = mpi_obj.is_deployed;
            if is_deployed
                mpi_obj.do_logging(step,n_steps,0.01,[]);
            end

            this = this.return_results(step);
        end        
    end
    
end

