function val=check_angular_set_(val)
% function checks if single angular value one tries to set is correct
%
if ~isnumeric(val)
    error('HERBERT:oriented_lattice:invalid_argument',...
        'angular value has to be numeric but it is: %s',...
        evalc('disp(val)'));
end
if numel(val)>1
    error('HERBERT:oriented_lattice:invalid_argument',...
        'angular value has to have a single value but it is array of %d elements',...
        numel(val));
end
if abs(val)>360
    error('HERBERT:oriented_lattice:invalid_argument',...
        'angular value should be in the range of +-360 deg but it equal to: %g',...
        val);
end
