#!groovy

pipeline {
    agent {
        label env.AGENT
    }

    stages {

        stage('Build') {
            steps {
                sh '''
                    module load cmake/\$CMAKE_VERSION &&
                    module load matlab/\$MATLAB_VERSION &&
                    module load gcc/\$GCC_VERSION &&
                    ./tools/build_config/build.sh --build
                '''
        }
    }

        stage('Test') {
            steps {
                sh '''
                    module load cmake/\$CMAKE_VERSION &&
                    module load matlab/\$MATLAB_VERSION &&
                    module load gcc/\$GCC_VERSION &&
                    ./tools/build_config/build.sh --test
                '''
            }
        }

        stage('Package') {
            steps {
                sh './tools/build_config/build.sh --package'
            }
        }
    }

    post {
        always {
            deleteDir()
        }
    }
}
