#!groovy
/**
 * The following parameters must be provided by the Jenkins build job and must match available application
 * on the build target machine
 *
 *  - CMAKE_VERSION: The version of CMake to run the build with
 *  - GCC_VERSION: The version of GCC to build with
 *  - MATLAB_VERSION: The release number of the Matlab to load
 *  - CLANG_VERSION: The version of CLang tooling to load to provide the clang-tidy code-style checks
 */
def post_github_status(String state, String message) {
    withCredentials([string(credentialsId: 'GitHub_API_Token',
            variable: 'api_token')]) {
        sh """
            curl -H "Authorization: token ${api_token}" \
                --request POST \
                --data '{"state": "${state}", \
                         "description": "${message}", \
                         "target_url": "$BUILD_URL", \
                         "context": "$JOB_BASE_NAME"}' \
                $PR_STATUSES_URL > /dev/null
        """
            }
}

pipeline {
    agent {
        label env.AGENT
    }

    stages {

        stage('Notify') {
            steps {
                post_github_status("pending", "The build is running")
            }
        }

        stage('Build') {
            steps {
                sh '''
                    module load cmake/\$CMAKE_VERSION &&
                    module load matlab/\$MATLAB_VERSION &&
                    module load gcc/\$GCC_VERSION &&
                    module load clang/\$CLANG_VERSION &&
                    ./tools/build_config/build.sh --build
                '''
            }
        }

        stage('Test') {
            steps {
                sh '''
                    module load cmake/\$CMAKE_VERSION &&
                    module load matlab/\$MATLAB_VERSION &&
                    module load gcc/\$GCC_VERSION &&
                    ./tools/build_config/build.sh --test
                '''
            }
        }

        stage('Package') {
            steps {
                sh './tools/build_config/build.sh --package'
            }
        }
    }

    post {
        always {
            // archive CTest results file
            archiveArtifacts(
                artifacts: 'build/Testing/**/*.xml',
                fingerprint: true
            )

            recordIssues(
                tools: [
                    clangTidy()
                ]
            )

            xunit (
                testTimeMargin: '3000',
                thresholdMode: 1,
                thresholds: [
                    skipped(failureThreshold: '0'),
                    failed(failureThreshold: '0')
                ],
                tools: [
                    CTest(
                        pattern: 'build/Testing/**/*.xml',
                        deleteOutputFiles: true,
                        failIfNotNew: false,
                        skipNoTestFiles: true,
                        stopProcessingIfError: true
                    )
                ]
            )
        }

        success {
            post_github_status("success", "The build succeeded")
        }

        failure {
            post_github_status("failure", "The build failed")
        }

        cleanup {
            deleteDir()
        }
    }
}
