%   'mc_contributions'  Define the contributing components to the resolution
%                       function. This is a structure with fields set to
%                       true or false accordingly. To generate the
%                       structure use the function tobyfit_mc_contributions.
%                       Type >> help tobyfit_mc_contributions for details
%                       Default: all components contribute
%
%   'mc_npoints'        Sets the number of Monte Carlo samplings per pixel.
%                       e.g. (...,'mc_npoints',100,...)
%                       Default: 10 (usually good for a first estimate)
%
%   'refine_crystal'    Options controlling refinement of crystal orientation 
%                       and lattice parameters. This is a structure, which can be
%                       generated by the function tobyfit_refine_crystal_options.
%                       Type >> help tobyfit_refine_crystal_options for details.
%                       Default: No refinement
%
%   'refine_moderator'  Options controlling refinement of moderator parameters.
%                       This is a structure, which can be generated by the
%                       function tobyfit_refine_moderator_options. Type
%                       >> help tobyfit_refine_moderator_options for
%                       details.
%                       Default: No refinement
