function data=getblock(fid)

% this function is used to read in the spe bock in the binary file
% generated by gen_hkle. It assumes that the file is already opened for
% reading and that fid is the file pointer associated with it. 
%
% output:
%   data.psi: psi angle
%   data.cu: u crystal axis (see mslice)
%   data.cv: v crystal axis (see mslice)
%   data.file: file name
%   data.size: size(1)=number of detectors; size(2)=number of energy bins
%   data.v: array containing the values along u1, u2, u3
%   data.en: vector containing the energy bins
%   data.S: Intensity vector
%   data.ERR: error vector

% Author:
%   J. van Duijn     01/06/2005
% Modified:
%
% Horace v0.1   J.Van Duijn, T.G.Perring

[data.psi,count]= fread(fid, 1, 'float32');
[data.cu,count]= fread(fid, 3, 'float32');
data.cu= data.cu';
[data.cv,count]= fread(fid, 3, 'float32');
data.cv=data.cv';
[n,count]=fread(fid, 1, 'int32');
[data.file,count]=fread(fid, n, '*char');
data.file=data.file';
[data.size,count]= fread(fid,2,'int32');
sizet= data.size(1)*data.size(2);
[data.v,count]= fread(fid,[3,sizet], 'float32');
%data.v=reshape(data.v, sizet,3);
% data.v=data.v';
[data.en,count]= fread(fid,[1,data.size(2)],'float32');
[data.S,count]= fread(fid,[1,sizet],'float32');
[data.ERR,count]= fread(fid,[1,sizet],'float32');