function data = readgrid (binfil)
% Read data from binary file containing one, two, three or four dimensional dataset.
%
% Syntax:
%   >> data = readgrid (binfil)
%
% Input:
% -------
%   binfil  Binary grid file, of the type generated by grid_hkle.m or slice_3d, and
%   contains data with the following content:
%
% Output:
% -------
%   data    Dataset containng the data read fromt he file
%

% Original author: J. van Duijn
%
% $Revision$ ($Date$)
%
% Horace v0.1   J. van Duijn, T.G.Perring

fid = fopen(binfil,'r');
disp('Reading binary file ...');

% Read header information
data.file = binfil;
data = get_header(fid,data);
if strcmp(data.grid,'spe')
    fclose(fid);
    error ('Error: Can only read orthogonal grid data ');
end

% Read grid information and the data
data = get_grid_data (fid, data)

fclose(fid);
