function data = readgrid (binfil)
% Read data from binary file containing one, two, three or four dimensional dataset.
%
% Syntax:
%   >> data = readgrid (binfil)
%
% Input:
% -------
%   binfil  Binary grid file, of the type generated by slice_4d or slice_3d
%
% Output:
% -------
%   data    Dataset containng the data read fromt he file
%

% Original author: J. van Duijn
%
% $Revision$ ($Date$)
%
% Horace v0.1   J. van Duijn, T.G.Perring

if nargin>0
    if isa_size(binfil,'row','char')
        if (exist(binfil,'file')==2)
            file_internal = binfil;
        else
            file_internal = genie_getfile(binfil);
        end
    else
        file_internal = genie_getfile;
    end
else
    file_internal = genie_getfile;
end
if (isempty(file_internal))
    error ('No file given')
end

fid = fopen(file_internal,'r');
disp('Reading binary file ...');

% Read header information
data.file = file_internal;
data = get_header(fid, data);
if ~strcmp(data.grid,'orthogonal-grid')
    fclose(fid);
    error ('Error: Can only read orthogonal grid data ');
end

% Read grid information and the data
ndim = length(data.pax);
data = get_grid_data(fid, ndim, data);

fclose(fid);

% Create class from structure
data = dnd_create(data);
