function data=readheader(binfil)

% this function obtains the header information contained in the binary file
% generated by gen_hkle.m and contains the following information
%
%       data.title_label: title label
%       data.ei: value of ei
%       data.a: a axis
%       data.b: b axis
%       data.c: c axis
%       data.alpha: alpha
%       data.beta: beta
%       data.gamma: gamma
%       data.u1: viewing axis u1 (Q)
%       data.u2: viewing axis u2 (Q)
%       data.u3: viewing axis u3 (Q)
%       data.u4: viewing axis u4 (this is energy)
%       data.nfiles:
%
% uses 

% Author:
%   J. van Duijn     01/06/2005
% Modified:
%
% Horace v0.1   J.Van Duijn, T.G.Perring

fid = fopen(binfil,'r');
data= getheader(fid);
fclose(fid);