function [figureHandle, axesHandle, plotHandle] = throw_unavailable_( ...
                obj,method,varargin)
% Throw method unavailable
error(['HORACE:',class(obj),':runtime_error'],...
    'Method %s is not avalible for object of class %s', ...
    method,class(obj))
