        !COMPILER-GENERATED INTERFACE MODULE: Mon Jul 13 12:13:45 2009
        MODULE LOAD_SPE_HEADER_mod
          INTERFACE 
            SUBROUTINE LOAD_SPE_HEADER(NDET,NE,FILENAME)
              INTEGER(KIND=4) :: NDET
              INTEGER(KIND=4) :: NE
              CHARACTER(*) :: FILENAME
            END SUBROUTINE LOAD_SPE_HEADER
          END INTERFACE 
        END MODULE LOAD_SPE_HEADER_mod
