        !COMPILER-GENERATED INTERFACE MODULE: Mon Jul 13 12:13:39 2009
        MODULE MEXFUNCTION_mod
          INTERFACE 
            SUBROUTINE MEXFUNCTION(NLHS,PLHS,NRHS,PRHS)
              INTEGER(KIND=4) :: NLHS
              INTEGER(KIND=4) :: PLHS(*)
              INTEGER(KIND=4) :: NRHS
              INTEGER(KIND=4) :: PRHS(*)
            END SUBROUTINE MEXFUNCTION
          END INTERFACE 
        END MODULE MEXFUNCTION_mod
