function detector_array = get_default_detector_array_from_detpar(detpar)
%GET_DEFAULT_DETECTOR_ARRAY_FROM_DETPAR Create a detector array instance from the minimal information in the detpar object.
%
% Return a detector array of He3 tubes in a single detector bank

detector = get_default_detector_from_detpar(detpar);

detector_array = IX_detector_array( ...
    detpar.group, ...
    detpar.x2(:), ...
    detpar.phi(:), ...
    detpar.azim(:),...
    detector);
end
