function build_version_h(pack_folder)
% Build Horace/herbert version file used by C++ code
%
% Input: location of the upper root folder of the package (where
% _LowLevelCode is located)
%
% using predefined
%
version_file = 'version.h';
ver_file_fp = fullfile(pack_folder,'_LowLevelCode','cpp','utility',version_file);
if is_file(ver_file_fp)
    return;
end
[~,pack_name] = fileparts(pack_folder);
%
version_template = fullfile(pack_folder,'VERSION');
fh_source = fopen(version_template );
if fh_source<1
    error('HERBERT_MEX:runtime_error',...
        ' Can not open version template %s',...
        version_template);
end
clob_in = onCleanup(@()fclose(fh_source));
ver = fscanf(fh_source,'%s');
%
fh_targ = fopen(ver_file_fp,'w');
clob_ou = onCleanup(@()fclose(fh_targ));
build_version = sprintf("%s from %s",ver,date);
fprintf(fh_targ,['namespace %s {\n',...
    '    constexpr char VERSION[] = "%s";\n}'],...
    pack_name,build_version);
init_version = which('herbert_get_build_version');
clear clob_ou;
cont = {'% This file is auto-generated by herbert/build_version_h. Do not edit, any edits may be lost.',...
'function out = herbert_get_build_version()',...
sprintf('out = ''%s''',build_version)};
fh_targ = fopen(init_version,'w');
clob_ou = onCleanup(@()fclose(fh_targ));
for i=1:numel(cont)
    fprintf(fh_targ,'%s\n',cont{i});
end
