function data=readheader(binfil)

% this function reads the header information contained in the binary file
% generated by gen_hkle.m and contains the following information
%
%       data.title_label: title label
%       data.ei: value of ei
%       data.a: a axis
%       data.a: b axis
%       data.a: c axis
%       data.alpha: alpha
%       data.beta: beta
%       data.gamma: gamma
%       data.u1: viewing axis u1 (Q)
%       data.u2: viewing axis u2 (Q)
%       data.u3: viewing axis u3 (Q)
%       data.u4: viewing axis u4 (this is energy)
%       data.nfiles:

disp('Reading header information ...')
fid = fopen(binfil,'r');
[n,count]= fread(fid,1,'int32');
[data.title,count]= fread(fid,n,'*char');
data.title= data.title';
[data.ei,count] = fread(fid,1,'float32');
[data.a,count] = fread(fid,1,'float32');
[data.b,count] = fread(fid,1,'float32');
[data.c,count] = fread(fid,1,'float32');
[data.alpha,count] = fread(fid,1,'float32');
[data.beta,count] = fread(fid,1,'float32');
[data.gamma,count] = fread(fid,1,'float32');
[data.u1,count] = fread(fid,4,'float32');
[data.u2,count] = fread(fid,4,'float32');
[data.u3,count] = fread(fid,4,'float32');
[data.u4,count] = fread(fid,4,'float32');
[data.nfiles,count] = fread(fid,1,'int32');
fclose(fid);