# For the list of CPack variables see https://cmake.org/cmake/help/v3.7/module/CPack.html

set(CPACK_RESOURCE_FILE_LICENSE "${CMAKE_SOURCE_DIR}/LICENSE")
set(CPACK_RESOURCE_FILE_README "${CMAKE_SOURCE_DIR}/README.md")
set(CPACK_PACKAGE_VERSION_MAJOR "${${PROJECT_NAME}_VERSION_MAJOR}")
set(CPACK_PACKAGE_VERSION_MINOR "${${PROJECT_NAME}_VERSION_MINOR}")
set(CPACK_PACKAGE_VERSION_PATCH "${${PROJECT_NAME}_VERSION_PATCH}")
set(CPACK_PACKAGE_FILE_NAME "${PROJECT_NAME}-${Herbert_FULL_VERSION}")
set(CPACK_TOPLEVEL_TAG "${PROJECT_NAME}-${PROJECT_VERSION}")
set(CPACK_SYSTEM_NAME "${CMAKE_SYSTEM_NAME}")

if(UNIX)
    set(CPACK_SOURCE_GENERATOR "TGZ;TZ;STGZ")
endif()

include(CPack)
