function [ok,err_mess]=finish_task_(obj,OtherMessage)
% set up tag, indicating that the job have finished and
% send message with output job results
%
% clear all existing messages intended or generated by this job
if exist('OtherMessage','var') && ~isempty(OtherMessage)
    mess = OtherMessage;
    if obj.return_results_    
        if isempty(mess.payload)
            mess.payload = obj.task_results_holder_;
        else
            mess.payload = {obj.task_results_holder_,mess.payload};            
        end
    end
else
    mess = aMessage('completed');
    if obj.return_results_
        mess.payload = obj.task_results_holder_;
    end
end
[ok,err_mess,fin_mess] = reduce_messages_(obj,mess);

if obj.labIndex == 1
    [ok,err_mess] = obj.control_node_exch.send_message(0,fin_mess);
    if ok == MESS_CODES.ok
        ok  = true;
    else
        ok  = false;
    end
end

