function [ok,err_mess]=finish_task_(obj)
% set up tag, indicating that the job have finished and
% send message with output job results
%
% clear all existing messages intended or generated by this job


mess = aMessage('completed');
if obj.return_results_
    mess.payload = obj.task_results_holder_;
end
[ok,err_mess,fin_mess] = reduce_messages_(obj,mess);

if ok && obj.labIndex == 1
    [ok,err_mess] = obj.control_node_exch.send_message(0,fin_mess);
    if ok == MESS_CODES.ok
        ok  = true;
    else
        ok  = false;
    end
end

